### ISSUE TITLE
OAuth 2.0 Error？

### ISSUE THREAD

**Issue by adapter00** [hardillb/node-red-alexa-home-skill-web#62]
Hi,
I install NODE-RED to the local mac and use it in cooperation with Alexa

Since I do not work since yesterday, I try to link my account from the Alexa application and I will fail
The following logs were displayed

```
ForbiddenError: Unable to load OAuth 2.0 transaction: HoeNWViD
    at SessionStore.load (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/oauth2orize/lib/txn/session.js:27:25)
    at transactionLoader (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/oauth2orize/lib/middleware/transactionLoader.js:42:24)
    at Layer.handle [as handle_request] (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/route.js:137:13)
    at app.post.oauthServer.decision.done.scope (/home/ec2-user/node-red-alexa-home-skill-web/index.js:483:3)
    at Layer.handle [as handle_request] (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/layer.js:95:5)
    at /home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/index.js:317:13)
    at /home/ec2-user/node-red-alexa-home-skill-web/node_modules/express/lib/router/index.js:284:7
```

What does this error mean?

**Comment by hardillb** [comment]
You should not be using this code, it is only for running the back end service. The node uses a single shared backend.

**Comment by hardillb** [comment]
What is your username?

**Comment by adapter00** [comment]
thx!
my username is adapterZero

**Comment by hardillb** [comment]
ok, all the oAuth tokens should have been removed from your account. Try and link the account again

**Comment by adapter00** [comment]
Thank you for a quick response!
i can link with it!
